### PR TITLE
Package as .net sdk 2.2/3.0 global tool

### PR DESCRIPTION
**Pull request by baronfel**
This is where I'm at with the global tool stuff.

I repackaged the binary as a global tool, and multi-target it to netcoreapp2.2 and netcoreapp3.0 so that it's forward-compatible with the upcoming 3.0 release.

But then the old FAKE runner didn't want to build the app, so I updated/migrated FAKE and the build script.

But then the C# compilation stuff changed significantly for .net core, so I reverse-engineered that.

But then I had to update the appveyor/travis build environments.

But then I ran into issues with assembly binding of the FCS compilation (so I might need to move to something similar to what I'm doing with the C# compilation).

### CODE REVIEW

**Comment by wallymathieu** [comment]
I merged master into this branch, I hope it was sort of correct.

**Comment by wallymathieu** [comment]
Could be that we can use https://travis-ci.community/t/net-core-3-0-preview/1936/6 in order to build preview of .net core

**Comment by wallymathieu** [comment]
I can compile the scripts locally, but of course there are other issues when running on travis and appveyor.

**Comment by wallymathieu** [comment]
Looks like the Appveyor problem is that there isn't dotnet core.

**Comment by baronfel** [comment]
Sorry for the silence on this, I've been a little swamped lately

**Comment by wallymathieu** [comment]
No worries! 😄

**Comment by wallymathieu** [comment]
Looks like @TheAngryByrd has updated https://github.com/TheAngryByrd/MiniScaffold so many of the problems we face are probably solved there

**Comment by wallymathieu** [comment]
I've squash my commits into a singe one in order to give less focus to my fiddling 😉

**Review by wallymathieu — APPROVED** [review]

**Comment by baronfel** [comment]
Awesome!

**Comment by wallymathieu** [comment]
Thanks @baronfel !

**Pull request merged**
