### PR TITLE
First merge of libraries

### PR DESCRIPTION
**Pull request by wallymathieu**
In order to be able to test components, I think there is a need to create a structure that contains the decomposed information.
Later on these structures can be used to generate the same strings found in @gentauro  SemanticVersioning.

I've started out with copying a lot of the reflection code from the @gentauro. I've changed things to work somewhat more like in SemVer.FromAssembly (generate structure). So I guess you could say that I'm rewriting both the code bases to become closer to each other.

- [x] assembly bump
- [x] Test of NetType.SumType
- [x] Test of NetType.RecordType
- [x] assemblies diff 
- [x] Test of NetType.Struct
- [x] Test of NetType.Module
- [x] Test of UnionCases decomposition
- [x] Test of Enum values decomposition

### CODE REVIEW

**Comment by wallymathieu** [comment]
Ping @gentauro

**Comment by ghost** [comment]
Hi @wallymathieu 

I'm actually mentioning you in my last blog post:

- http://blog.stermon.com/articles/2017/02/17/speaker-at-fsharp-exchange-2017

> Note: Oskar, sorry for not being able to work on the project at the moment.

It's due to I should have gone live at the end of last month and I'm still not ready for it (a delay of one month AT MOST).

So please bear with me :1234: 

But you are really doing some great work !!! :+1:

**Comment by wallymathieu** [comment]
Thanks for the compliment! I'm thinking that the next step is to add the NuGet code from [NuGet.fs](https://github.com/spisemisu/SpiseMisu.SemanticVersioning/blob/sync/src/SpiseMisu.SemanticVersioning/NuGet.fs)

**Comment by ghost** [comment]
Yeah, I already though on how to handle the `1000` different names that `dotnet` is getting:

- https://github.com/spisemisu/SpiseMisu.SemanticVersioning/blob/sync/src/SpiseMisu.SemanticVersioning/NuGet.fs#L19-L23

If we use my previous approach we will be locked to having to `build` -> `distribute` a new version for any new `name` that the MS Team comes up with.

What do you thing of the `Suave.io` approach? (I describe it in a `snippet` on my blog):

- http://blog.stermon.com/articles/2017/01/25/fsharp-extend-pattern-matching

This way you can choose the ones we have defined, and if you are using a new `NuGet` package we don't support, you can add a custom `dotnet` name (maybe build/preview versions)

**Comment by wallymathieu** [comment]
Is there some library that define the equivalence classes (so that we don't have to)? Maybe NuGet contains that code?

**Comment by wallymathieu** [comment]
I remember this being mentioned on slack:
https://github.com/NuGet/NuGet.Client/blob/c1add033fb9f5ec05c6032aeb3f1ad29522fbb63/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs#L384-L412
It would be helpful if we could use that

**Comment by wallymathieu** [comment]
But, yes the extend pattern matching is a nice way

**Comment by ghost** [comment]
Hmmmm, maybe thinking twice about it ... what if there are new features in newer .NET versions that we don't handle? Instead of giving false safety we should just say: "We don't handle that version of `dotnet`".

It might be the best (and easiest) solution for us.

**Comment by wallymathieu** [comment]
Indeed

**Pull request merged**
